[pinyin]
"汉溪长隆" = "han xi chang long"
"荆长路" = "jing chang lu"
"清远长隆" = "qing yuan chang long"
"长岸" = "chang an"
"长白岛" = "chang bai dao"
"长白南" = "chang bai nan"
"长湴" = "chang ban"
"长椿街" = "chang chun jie"
"长店堡" = "chang dian bao"
"长丰" = "chang feng"
"长风东街" = "chang feng dong jie"
"长风公园" = "chang feng gong yuan"
"长风街" = "chang feng jie"
"长福路" = "chang fu lu"
"长堽路" = "chang gang lu"
"长港路" = "chang gang lu"
"长广溪" = "chang guang xi"
"长湖" = "chang hu"
"长淮" = "chang huai"
"长泾" = "chang jing"
"长陵" = "chang ling"
"长岭陂" = "chang ling bei"
"长岭山" = "chang ling shan"
"长隆森林王国" = "chang long sen lin wang guo"
"长芦" = "chang lu"
"长平" = "chang ping"
"长庆" = "chang qing"
"长清路" = "chang qing lu"
"长阳" = "chang yang"
"长影世纪城" = "chang ying shi ji cheng"
"长圳" = "chang zhen"
"长洲" = "chang zhou"
"柏林" = "bai lin"
"柏林庄" = "bai lin zhuang"
